export const environment = {
  production: true,
  myCustomProp: 'test-property',
  staff_listPage_firstName: 'First Name',
  staff_listPage_lastName: 'Last Name',
  staff_listPage_mobileNumber: 'Mobile Number',
  staff_listPage_emailId: 'E-mail Id',
  staff_listPage_placeholder: 'Search...',
  staff_listPage_refresh_button: 'Refresh',
  staff_listPage_update_button: 'Update',
  staff_listPage_nostaffMessage: 'There are no staffs registered yet.',
  addStaff_placeHolder_firstName: 'First Name',
  addStaff_placeHolder_lastName: 'Last Name',
  addStaff_placeHolder_emailId: 'E-mail Id',
  addStaff_placeHolder_mobileNumber: 'Mobile Number',
  addStaff_placeHolder_address: 'Address',
  addStaff_placeHolder_city: 'City',
  addStaff_placeHolder_state: 'State',
  addStaff_firstName: 'First Name',
  addStaff_lastName: 'Last Name',
  addStaff_emailId: 'E-mail Id',
  addStaff_mobileNumber: 'Mobile Number',
  addStaff_address: 'Address',
  addStaff_city: 'City',
  addStaff_state: 'State',
  addStaff_groupName: 'Add Staff',
  addStaff_addbutton: 'Add',
  addStaff_updatebutton: 'Update',
  addStaff_addRecordbutton: 'Add Record',
  addStaff_updateRecordbutton: 'Update Record',
  addStaff_pageMessage: 'Please enter all fields marked by *',
  location_listPage_addDutyLocation_button : 'Add Duty Location',
  location_listPage_addDutyLocation_successMsg : 'Success !!',
  location_listPage_addDutyLocation_errorMsg : 'Error !!',
  location_listPage_addDutyLocation_LocationUpdated : 'The location details have been updated.',
  location_listPage_addDutyLocation_LocationUpdateFailed : 'Sorry, unable to complete the operation. Please try again.',
  location_listPage_location : 'Location',
  location_listPage_address : 'Address',
  location_listPage_city : 'City',
  location_listPage_search : 'Search...',
  location_listPage_refreshbutton : 'Refresh',
  location_listPage_noLocationRegMsg: 'There are no locations registered yet.',
  location_listPage_updateButton: 'Update',
  addLocation_placeholder_locationName: 'Location Name',
  addLocation_placeholder_locationAddress: 'Location Address',
  addLocation_placeholder_mobileNumber: 'Mobile Number',
  addLocation_placeholder_address: 'Address',
  addLocation_placeholder_city: 'City',
  addLocation_placeholder_state: 'State',
  addLocation_locationName: 'Location Name',
  addLocation_locationAddress: 'Location Address',
  addLocation_mobileNumber: 'Mobile Number',
  addLocation_address: 'Address',
  addLocation_city: 'City',
  addLocation_state: 'State',
  addLocation_groupName: 'Add Location',
  updateLocation_groupName: 'Update Location',
  addLocation_pageMessage: 'Please enter all fields marked by *',
  addLocation_addButton: 'Add',
  addLocation_updateButton: 'Update',
  device_listPage_imei: 'IMEI',
  device_listPage_staffName: 'Staff Name',
  device_listPage_isActive: 'Is Active',
  device_listPage_search: 'Search...',
  device_listPage_successMsg : 'Success !!',
  device_listPage_errorMsg : 'Error !!',
  device_listPage_deviceUpdated : 'The device details have been updated.',
  device_listPage_deviceUpdateFailed : 'Sorry, unable to complete the operation. Please try again.',
  device_listPage_noDeviceRegMsg : 'There are no devices registered yet.',
  addDevice_placeHolder_deviceIMEI: 'Device IMEI',
  addDevice_placeHolder_staffName: 'Staff Name',
  addDevice_placeHolder_isActive: 'Is Active',
  addDevice_groupName: 'Add Device',
  updateDevice_groupName: 'Update Device',
  addDevice_addbutton: 'Add',
  addDevice_updatebutton: 'Update',
  addDevice_refreshbutton: 'Refresh',
  addDevice_pageMessage: 'Please enter all fields marked by *',
  reports_listPage_dropDownLabel : 'All Locations',
  reports_listPage_startDate : 'Start',
  reports_listPage_endDate : 'End',
  reports_listPage_locationName : 'Location Name',
  reports_listPage_visiting : 'Visiting',
  reports_listPage_startTime : 'Start Time',
  reports_listPage_endTime: 'End Time',
  reports_listPage_visitSummary : 'Visiting Summary',
  reports_listPage_noReportRegYetMsg : 'There are no reports registered yet.',
  reports_listPage_reportByLabel : 'Report By :'
};
